spring:
  application:
    name: admin-expenses

  datasource:
    url: jdbc:postgresql://localhost:5432/expense
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081