spring:
  application:
    name: admin-expenses
#  cloud:
#    config:
#      discovery:
#        enabled: true
#        service-id: config-service
#  config:
#    import: optional:configserver:.

  datasource:
    url: jdbc:postgresql://localhost:5432/expense
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health, info
  info:
    env:
      enabled: true

info:
  app:
    name: admin-expense
    description: admin expense service
    version: 1.0.0